// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQKNsDmeWRHjp3OZKMhiEYFrBOBetzf8',
    appId: '1:385339386904:web:5070478b43f6ca153e676d',
    messagingSenderId: '385339386904',
    projectId: 'stage-yool-education-98ae2',
    authDomain: 'stage-yool-education-98ae2.firebaseapp.com',
    databaseURL: 'https://stage-yool-education-98ae2-default-rtdb.firebaseio.com',
    storageBucket: 'stage-yool-education-98ae2.appspot.com',
    measurementId: 'G-KL4CLS07L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkY_-9myTsO4Ml9xrLFMDhuFC3AfP8fu0',
    appId: '1:385339386904:android:7cf81c043602f9eb3e676d',
    messagingSenderId: '385339386904',
    projectId: 'stage-yool-education-98ae2',
    databaseURL: 'https://stage-yool-education-98ae2-default-rtdb.firebaseio.com',
    storageBucket: 'stage-yool-education-98ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpHv1URdEr1GfW1KAQVFX7a7hNNN0UJk',
    appId: '1:385339386904:ios:d9fc0b29e82b1f723e676d',
    messagingSenderId: '385339386904',
    projectId: 'stage-yool-education-98ae2',
    databaseURL: 'https://stage-yool-education-98ae2-default-rtdb.firebaseio.com',
    storageBucket: 'stage-yool-education-98ae2.appspot.com',
    iosClientId: '385339386904-0h1s8krloeb4kpm4ojnek80b5pvckr0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.yoolProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkpHv1URdEr1GfW1KAQVFX7a7hNNN0UJk',
    appId: '1:385339386904:ios:f6cd5cca044423b43e676d',
    messagingSenderId: '385339386904',
    projectId: 'stage-yool-education-98ae2',
    databaseURL: 'https://stage-yool-education-98ae2-default-rtdb.firebaseio.com',
    storageBucket: 'stage-yool-education-98ae2.appspot.com',
    iosClientId: '385339386904-hfldq74qhp71gsg8e7bi4dl7up8er1ad.apps.googleusercontent.com',
    iosBundleId: 'com.example.yoolProject.RunnerTests',
  );
}
